module.exports.SELECT_CHIEF_REQUEST= 'SELECT_CHIEF_REQUEST';
module.exports.OPEN_CHEIF_REQUEST_DRAWER = 'OPEN_CHEIF_REQUEST_DRAWER';
module.exports.CLOSE_CHEIF_REQUEST_DRAWER = 'CLOSE_CHEIF_REQUEST_DRAWER';