module.exports.SELECT_CHEIF_REQUEST = 'SELECT_CHEIF_REQUEST';
module.exports.UPDATE_FIRST_DRAWER_DATA = 'UPDATE_FIRST_DRAWER_DATA';
module.exports.OPEN_DRAWER_STATE = 'OPEN_DRAWER_STATE';
module.exports.CLOSE_DRAWER_STATE = 'CLOSE_DRAWER_STATE';